FROM debian:bullseye-slim

RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        tzdata \
        make \
        cmake \
        clang \
        clang-format \
        gcc \
        git \
        python3 \
        python-is-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV \
    TZ=Asia/Tokyo
